[tool.poetry]
name = "straticor"
version = "0.0.1"
description = "Correlate stratigraphic columns"
authors = ["Sebástian Narváez"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
